name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnowdb"
database_id = "f9069072-9105-4889-b84c-5546b9aa3ecd"
